
// import './globals.css'
import { Appbar } from '@/components/Appbar'
// import Appbarcomponent from '@/components/Appbarcomponent'
import Footer from '@/components/footer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Appbar/>
        <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  )
}
